DROP TABLE IF EXISTS auto_plan;

CREATE TABLE auto_plan (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           plan_id VARCHAR(100) NOT NULL,
                           rank_id BIGINT NOT NULL DEFAULT 0,
                           team_id VARCHAR(100) NOT NULL,
                           plan_name VARCHAR(255) NOT NULL,
                           task_type SMALLINT NOT NULL DEFAULT 1,
                           status SMALLINT NOT NULL DEFAULT 1,
                           create_user_id VARCHAR(100) NOT NULL,
                           run_user_id VARCHAR(100) NOT NULL,
                           remark TEXT,
                           run_count BIGINT NOT NULL DEFAULT 0,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           deleted_at TIMESTAMP DEFAULT NULL,

                           PRIMARY KEY (id),
                           CONSTRAINT chk_auto_plan_run_count CHECK (run_count >= 0)
);

CREATE INDEX idx_plan_id ON auto_plan (plan_id);
CREATE INDEX idx_team_id ON auto_plan (team_id);

COMMENT ON TABLE auto_plan IS '自动化测试-计划表';

COMMENT ON COLUMN auto_plan.id IS '主键';
COMMENT ON COLUMN auto_plan.plan_id IS '计划ID';
COMMENT ON COLUMN auto_plan.rank_id IS '序号ID';
COMMENT ON COLUMN auto_plan.team_id IS '团队ID';
COMMENT ON COLUMN auto_plan.plan_name IS '计划名称';
COMMENT ON COLUMN auto_plan.task_type IS '计划类型：1-普通任务，2-定时任务';
COMMENT ON COLUMN auto_plan.status IS '计划状态1:未开始,2:进行中';
COMMENT ON COLUMN auto_plan.create_user_id IS '创建人id';
COMMENT ON COLUMN auto_plan.run_user_id IS '运行人id';
COMMENT ON COLUMN auto_plan.remark IS '备注';
COMMENT ON COLUMN auto_plan.run_count IS '运行次数';
COMMENT ON COLUMN auto_plan.created_at IS '创建时间';
COMMENT ON COLUMN auto_plan.updated_at IS '更新时间';
COMMENT ON COLUMN auto_plan.deleted_at IS '删除时间';

DROP TABLE IF EXISTS auto_plan_email;

CREATE TABLE auto_plan_email (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 plan_id VARCHAR(100) NOT NULL DEFAULT '0',
                                 team_id VARCHAR(100) NOT NULL,
                                 email VARCHAR(255) NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 deleted_at TIMESTAMP DEFAULT NULL,

                                 PRIMARY KEY (id)
);

COMMENT ON TABLE auto_plan_email IS '自动化测计划—收件人邮箱表';

COMMENT ON COLUMN auto_plan_email.id IS '主键';
COMMENT ON COLUMN auto_plan_email.plan_id IS '计划ID';
COMMENT ON COLUMN auto_plan_email.team_id IS '团队ID';
COMMENT ON COLUMN auto_plan_email.email IS '邮箱';
COMMENT ON COLUMN auto_plan_email.created_at IS '创建时间';
COMMENT ON COLUMN auto_plan_email.updated_at IS '修改时间';
COMMENT ON COLUMN auto_plan_email.deleted_at IS '删除时间';


DROP TABLE IF EXISTS auto_plan_report;

CREATE TABLE auto_plan_report (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  report_id VARCHAR(100) NOT NULL,
                                  report_name VARCHAR(125) NOT NULL,
                                  plan_id VARCHAR(100) NOT NULL,
                                  rank_id BIGINT NOT NULL DEFAULT 0,
                                  plan_name VARCHAR(255) NOT NULL,
                                  team_id VARCHAR(100) NOT NULL,
                                  task_type INTEGER NOT NULL DEFAULT 0,
                                  task_mode INTEGER NOT NULL DEFAULT 0,
                                  control_mode SMALLINT NOT NULL DEFAULT 0,
                                  scene_run_order SMALLINT NOT NULL DEFAULT 1,
                                  test_case_run_order SMALLINT NOT NULL DEFAULT 1,
                                  run_duration_time BIGINT NOT NULL DEFAULT 0,
                                  status SMALLINT NOT NULL DEFAULT 1,
                                  run_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                                  remark TEXT NOT NULL,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  deleted_at TIMESTAMP DEFAULT NULL,

                                  PRIMARY KEY (id)
);

CREATE INDEX idx_report_id ON auto_plan_report (report_id);
CREATE INDEX idx_team_id ON auto_plan_report (team_id);

COMMENT ON TABLE auto_plan_report IS '自动化测试计划-报告表';

COMMENT ON COLUMN auto_plan_report.id IS '主键';
COMMENT ON COLUMN auto_plan_report.report_id IS '报告ID';
COMMENT ON COLUMN auto_plan_report.report_name IS '报告名称';
COMMENT ON COLUMN auto_plan_report.plan_id IS '计划ID';
COMMENT ON COLUMN auto_plan_report.rank_id IS '序号ID';
COMMENT ON COLUMN auto_plan_report.plan_name IS '计划名称';
COMMENT ON COLUMN auto_plan_report.team_id IS '团队ID';
COMMENT ON COLUMN auto_plan_report.task_type IS '任务类型';
COMMENT ON COLUMN auto_plan_report.task_mode IS '运行模式：1-按测试用例运行';
COMMENT ON COLUMN auto_plan_report.control_mode IS '控制模式：0-集中模式，1-单独模式';
COMMENT ON COLUMN auto_plan_report.scene_run_order IS '场景运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_report.test_case_run_order IS '测试用例运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_report.run_duration_time IS '任务运行持续时长';
COMMENT ON COLUMN auto_plan_report.status IS '报告状态1:进行中，2:已完成';
COMMENT ON COLUMN auto_plan_report.run_user_id IS '启动人id';
COMMENT ON COLUMN auto_plan_report.remark IS '备注';
COMMENT ON COLUMN auto_plan_report.created_at IS '创建时间（执行时间）';
COMMENT ON COLUMN auto_plan_report.updated_at IS '更新时间';
COMMENT ON COLUMN auto_plan_report.deleted_at IS '删除时间';


