DROP TABLE IF EXISTS auto_plan;

CREATE TABLE auto_plan (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           plan_id VARCHAR(100) NOT NULL,
                           rank_id BIGINT NOT NULL DEFAULT 0,
                           team_id VARCHAR(100) NOT NULL,
                           plan_name VARCHAR(255) NOT NULL,
                           task_type SMALLINT NOT NULL DEFAULT 1,
                           status SMALLINT NOT NULL DEFAULT 1,
                           create_user_id VARCHAR(100) NOT NULL,
                           run_user_id VARCHAR(100) NOT NULL,
                           remark TEXT,
                           run_count BIGINT NOT NULL DEFAULT 0,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           deleted_at TIMESTAMP DEFAULT NULL,

                           PRIMARY KEY (id),
                           CONSTRAINT chk_auto_plan_run_count CHECK (run_count >= 0)
);

CREATE INDEX idx_plan_id ON auto_plan (plan_id);
CREATE INDEX idx_team_id ON auto_plan (team_id);

COMMENT ON TABLE auto_plan IS '自动化测试-计划表';

COMMENT ON COLUMN auto_plan.id IS '主键';
COMMENT ON COLUMN auto_plan.plan_id IS '计划ID';
COMMENT ON COLUMN auto_plan.rank_id IS '序号ID';
COMMENT ON COLUMN auto_plan.team_id IS '团队ID';
COMMENT ON COLUMN auto_plan.plan_name IS '计划名称';
COMMENT ON COLUMN auto_plan.task_type IS '计划类型：1-普通任务，2-定时任务';
COMMENT ON COLUMN auto_plan.status IS '计划状态1:未开始,2:进行中';
COMMENT ON COLUMN auto_plan.create_user_id IS '创建人id';
COMMENT ON COLUMN auto_plan.run_user_id IS '运行人id';
COMMENT ON COLUMN auto_plan.remark IS '备注';
COMMENT ON COLUMN auto_plan.run_count IS '运行次数';
COMMENT ON COLUMN auto_plan.created_at IS '创建时间';
COMMENT ON COLUMN auto_plan.updated_at IS '更新时间';
COMMENT ON COLUMN auto_plan.deleted_at IS '删除时间';

DROP TABLE IF EXISTS auto_plan_email;

CREATE TABLE auto_plan_email (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 plan_id VARCHAR(100) NOT NULL DEFAULT '0',
                                 team_id VARCHAR(100) NOT NULL,
                                 email VARCHAR(255) NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 deleted_at TIMESTAMP DEFAULT NULL,

                                 PRIMARY KEY (id)
);

COMMENT ON TABLE auto_plan_email IS '自动化测计划—收件人邮箱表';

COMMENT ON COLUMN auto_plan_email.id IS '主键';
COMMENT ON COLUMN auto_plan_email.plan_id IS '计划ID';
COMMENT ON COLUMN auto_plan_email.team_id IS '团队ID';
COMMENT ON COLUMN auto_plan_email.email IS '邮箱';
COMMENT ON COLUMN auto_plan_email.created_at IS '创建时间';
COMMENT ON COLUMN auto_plan_email.updated_at IS '修改时间';
COMMENT ON COLUMN auto_plan_email.deleted_at IS '删除时间';


DROP TABLE IF EXISTS auto_plan_report;

CREATE TABLE auto_plan_report (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  report_id VARCHAR(100) NOT NULL,
                                  report_name VARCHAR(125) NOT NULL,
                                  plan_id VARCHAR(100) NOT NULL,
                                  rank_id BIGINT NOT NULL DEFAULT 0,
                                  plan_name VARCHAR(255) NOT NULL,
                                  team_id VARCHAR(100) NOT NULL,
                                  task_type INTEGER NOT NULL DEFAULT 0,
                                  task_mode INTEGER NOT NULL DEFAULT 0,
                                  control_mode SMALLINT NOT NULL DEFAULT 0,
                                  scene_run_order SMALLINT NOT NULL DEFAULT 1,
                                  test_case_run_order SMALLINT NOT NULL DEFAULT 1,
                                  run_duration_time BIGINT NOT NULL DEFAULT 0,
                                  status SMALLINT NOT NULL DEFAULT 1,
                                  run_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                                  remark TEXT NOT NULL,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  deleted_at TIMESTAMP DEFAULT NULL,

                                  PRIMARY KEY (id)
);

CREATE INDEX idx_report_id ON auto_plan_report (report_id);
CREATE INDEX idx_team_id ON auto_plan_report (team_id);

COMMENT ON TABLE auto_plan_report IS '自动化测试计划-报告表';

COMMENT ON COLUMN auto_plan_report.id IS '主键';
COMMENT ON COLUMN auto_plan_report.report_id IS '报告ID';
COMMENT ON COLUMN auto_plan_report.report_name IS '报告名称';
COMMENT ON COLUMN auto_plan_report.plan_id IS '计划ID';
COMMENT ON COLUMN auto_plan_report.rank_id IS '序号ID';
COMMENT ON COLUMN auto_plan_report.plan_name IS '计划名称';
COMMENT ON COLUMN auto_plan_report.team_id IS '团队ID';
COMMENT ON COLUMN auto_plan_report.task_type IS '任务类型';
COMMENT ON COLUMN auto_plan_report.task_mode IS '运行模式：1-按测试用例运行';
COMMENT ON COLUMN auto_plan_report.control_mode IS '控制模式：0-集中模式，1-单独模式';
COMMENT ON COLUMN auto_plan_report.scene_run_order IS '场景运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_report.test_case_run_order IS '测试用例运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_report.run_duration_time IS '任务运行持续时长';
COMMENT ON COLUMN auto_plan_report.status IS '报告状态1:进行中，2:已完成';
COMMENT ON COLUMN auto_plan_report.run_user_id IS '启动人id';
COMMENT ON COLUMN auto_plan_report.remark IS '备注';
COMMENT ON COLUMN auto_plan_report.created_at IS '创建时间（执行时间）';
COMMENT ON COLUMN auto_plan_report.updated_at IS '更新时间';
COMMENT ON COLUMN auto_plan_report.deleted_at IS '删除时间';


DROP TABLE IF EXISTS auto_plan_task_conf;

CREATE TABLE auto_plan_task_conf (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     plan_id VARCHAR(100) NOT NULL DEFAULT '0',
                                     team_id VARCHAR(100) NOT NULL,
                                     task_type SMALLINT NOT NULL DEFAULT 0,
                                     task_mode SMALLINT NOT NULL DEFAULT 1,
                                     scene_run_order SMALLINT NOT NULL DEFAULT 1,
                                     test_case_run_order SMALLINT NOT NULL DEFAULT 1,
                                     run_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     deleted_at TIMESTAMP DEFAULT NULL,

                                     PRIMARY KEY (id)
);

CREATE INDEX idx_plan_id ON auto_plan_task_conf (plan_id);

COMMENT ON TABLE auto_plan_task_conf IS '自动化测试—普通任务配置表';

COMMENT ON COLUMN auto_plan_task_conf.id IS '配置ID';
COMMENT ON COLUMN auto_plan_task_conf.plan_id IS '计划ID';
COMMENT ON COLUMN auto_plan_task_conf.team_id IS '团队ID';
COMMENT ON COLUMN auto_plan_task_conf.task_type IS '任务类型：1-普通模式，2-定时任务';
COMMENT ON COLUMN auto_plan_task_conf.task_mode IS '运行模式：1-按照用例执行';
COMMENT ON COLUMN auto_plan_task_conf.scene_run_order IS '场景运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_task_conf.test_case_run_order IS '用例运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_task_conf.run_user_id IS '运行人用户ID';
COMMENT ON COLUMN auto_plan_task_conf.created_at IS '创建时间';
COMMENT ON COLUMN auto_plan_task_conf.updated_at IS '更新时间';
COMMENT ON COLUMN auto_plan_task_conf.deleted_at IS '删除时间';


DROP TABLE IF EXISTS auto_plan_timed_task_conf;

CREATE TABLE auto_plan_timed_task_conf (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                           plan_id VARCHAR(100) NOT NULL DEFAULT '0',
                                           team_id VARCHAR(100) NOT NULL,
                                           frequency INTEGER NOT NULL DEFAULT 0,
                                           task_exec_time BIGINT NOT NULL DEFAULT 0,
                                           task_close_time BIGINT NOT NULL DEFAULT 0,
                                           task_type SMALLINT NOT NULL DEFAULT 2,
                                           task_mode SMALLINT NOT NULL DEFAULT 1,
                                           scene_run_order SMALLINT NOT NULL DEFAULT 1,
                                           test_case_run_order SMALLINT NOT NULL DEFAULT 1,
                                           status SMALLINT NOT NULL DEFAULT 0,
                                           run_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           deleted_at TIMESTAMP DEFAULT NULL,

                                           PRIMARY KEY (id),

                                           CONSTRAINT chk_auto_plan_timed_task_conf_frequency
                                               CHECK (frequency >= 0),

                                           CONSTRAINT chk_auto_plan_timed_task_conf_task_exec_time
                                               CHECK (task_exec_time >= 0),

                                           CONSTRAINT chk_auto_plan_timed_task_conf_task_close_time
                                               CHECK (task_close_time >= 0)
);

CREATE INDEX idx_plan_id
    ON auto_plan_timed_task_conf (plan_id);

COMMENT ON TABLE auto_plan_timed_task_conf IS '自动化测试-定时任务配置表';

COMMENT ON COLUMN auto_plan_timed_task_conf.id IS '表id';
COMMENT ON COLUMN auto_plan_timed_task_conf.plan_id IS '计划id';
COMMENT ON COLUMN auto_plan_timed_task_conf.team_id IS '团队id';
COMMENT ON COLUMN auto_plan_timed_task_conf.frequency IS '任务执行频次: 0-一次，1-每天，2-每周，3-每月';
COMMENT ON COLUMN auto_plan_timed_task_conf.task_exec_time IS '任务执行时间';
COMMENT ON COLUMN auto_plan_timed_task_conf.task_close_time IS '任务结束时间';
COMMENT ON COLUMN auto_plan_timed_task_conf.task_type IS '任务类型：1-普通任务，2-定时任务';
COMMENT ON COLUMN auto_plan_timed_task_conf.task_mode IS '运行模式：1-按照用例执行';
COMMENT ON COLUMN auto_plan_timed_task_conf.scene_run_order IS '场景运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_timed_task_conf.test_case_run_order IS '测试用例运行次序：1-顺序执行，2-同时执行';
COMMENT ON COLUMN auto_plan_timed_task_conf.status IS '任务状态：0-未启用，1-运行中，2-已过期';
COMMENT ON COLUMN auto_plan_timed_task_conf.run_user_id IS '运行人用户ID';
COMMENT ON COLUMN auto_plan_timed_task_conf.created_at IS '创建时间';
COMMENT ON COLUMN auto_plan_timed_task_conf.updated_at IS '更新时间';
COMMENT ON COLUMN auto_plan_timed_task_conf.deleted_at IS '删除时间';

DROP TABLE IF EXISTS company;

CREATE TABLE company (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         company_id VARCHAR(100) NOT NULL,
                         name VARCHAR(100) NOT NULL DEFAULT '',
                         logo VARCHAR(255) NOT NULL DEFAULT '',
                         expire_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at TIMESTAMP DEFAULT NULL,

                         PRIMARY KEY (id)
);

CREATE INDEX idx_company_id
    ON company (company_id);

COMMENT ON TABLE company IS '企业表';

COMMENT ON COLUMN company.id IS '主键id';
COMMENT ON COLUMN company.company_id IS '企业id';
COMMENT ON COLUMN company.name IS '企业名称';
COMMENT ON COLUMN company.logo IS '企业logo';
COMMENT ON COLUMN company.expire_at IS '服务到期时间';


DROP TABLE IF EXISTS element;

CREATE TABLE element (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         element_id VARCHAR(100) NOT NULL,
                         element_type VARCHAR(10) NOT NULL,
                         team_id VARCHAR(100) NOT NULL,
                         name VARCHAR(255) NOT NULL,
                         parent_id VARCHAR(100) NOT NULL DEFAULT '0',
                         locators JSONB DEFAULT NULL,
                         sort INTEGER NOT NULL DEFAULT 0,
                         version INTEGER NOT NULL DEFAULT 0,
                         created_user_id VARCHAR(100) NOT NULL,
                         description TEXT NOT NULL,
                         source SMALLINT NOT NULL DEFAULT 0,
                         source_id VARCHAR(100) NOT NULL DEFAULT '',
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at TIMESTAMP DEFAULT NULL,

                         PRIMARY KEY (id)
);

CREATE INDEX idx_element_id
    ON element (element_id);

CREATE INDEX idx_team_id
    ON element (team_id);

COMMENT ON TABLE element IS '元素表';

COMMENT ON COLUMN element.id IS 'id';
COMMENT ON COLUMN element.element_id IS '全局唯一ID';
COMMENT ON COLUMN element.element_type IS '类型：文件夹，元素';
COMMENT ON COLUMN element.team_id IS '团队id';
COMMENT ON COLUMN element.name IS '名称';
COMMENT ON COLUMN element.parent_id IS '父级ID';
COMMENT ON COLUMN element.locators IS '定位元素属性';
COMMENT ON COLUMN element.sort IS '排序';
COMMENT ON COLUMN element.version IS '产品版本号';
COMMENT ON COLUMN element.created_user_id IS '创建人ID';
COMMENT ON COLUMN element.description IS '备注';
COMMENT ON COLUMN element.source IS '数据来源：0-元素管理，1-场景管理';
COMMENT ON COLUMN element.source_id IS '引用来源ID';
COMMENT ON COLUMN element.created_at IS '创建时间';
COMMENT ON COLUMN element.updated_at IS '更新时间';
COMMENT ON COLUMN element.deleted_at IS '删除时间';

DROP TABLE IF EXISTS global_variable;

CREATE TABLE global_variable (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 team_id VARCHAR(100) NOT NULL,
                                 type SMALLINT NOT NULL DEFAULT 0,
                                 var VARCHAR(255) NOT NULL,
                                 val TEXT NOT NULL,
                                 description TEXT NOT NULL,
                                 status SMALLINT NOT NULL DEFAULT 1,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 deleted_at TIMESTAMP DEFAULT NULL,

                                 PRIMARY KEY (id)
);

CREATE INDEX idx_team_id
    ON global_variable (team_id);

COMMENT ON TABLE global_variable IS '全局变量表';

COMMENT ON COLUMN global_variable.id IS '主键id';
COMMENT ON COLUMN global_variable.team_id IS '团队id';
COMMENT ON COLUMN global_variable.type IS '变量类型：1-全局变量，2-场景变量';
COMMENT ON COLUMN global_variable.var IS '变量名';
COMMENT ON COLUMN global_variable.val IS '变量值';
COMMENT ON COLUMN global_variable.description IS '描述';
COMMENT ON COLUMN global_variable.status IS '开关状态：1-开启，2-关闭';
COMMENT ON COLUMN global_variable.created_at IS '创建时间';
COMMENT ON COLUMN global_variable.updated_at IS '修改时间';
COMMENT ON COLUMN global_variable.deleted_at IS '删除时间';

DROP TABLE IF EXISTS machine;

CREATE TABLE machine (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         region VARCHAR(64) NOT NULL,
                         ip VARCHAR(16) NOT NULL,
                         port INTEGER NOT NULL,
                         name VARCHAR(200) NOT NULL,
                         cpu_usage REAL NOT NULL DEFAULT 0,
                         cpu_load_one REAL NOT NULL DEFAULT 0,
                         cpu_load_five REAL NOT NULL DEFAULT 0,
                         cpu_load_fifteen REAL NOT NULL DEFAULT 0,
                         mem_usage REAL NOT NULL DEFAULT 0,
                         disk_usage REAL NOT NULL DEFAULT 0,
                         max_goroutines BIGINT NOT NULL DEFAULT 0,
                         current_goroutines BIGINT NOT NULL DEFAULT 0,
                         server_type SMALLINT NOT NULL DEFAULT 1,
                         status SMALLINT NOT NULL DEFAULT 1,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at TIMESTAMP DEFAULT NULL,

                         PRIMARY KEY (id),

                         CONSTRAINT chk_machine_port
                             CHECK (port >= 0),

                         CONSTRAINT chk_machine_cpu_usage
                             CHECK (cpu_usage >= 0),

                         CONSTRAINT chk_machine_cpu_load_one
                             CHECK (cpu_load_one >= 0),

                         CONSTRAINT chk_machine_cpu_load_five
                             CHECK (cpu_load_five >= 0),

                         CONSTRAINT chk_machine_cpu_load_fifteen
                             CHECK (cpu_load_fifteen >= 0),

                         CONSTRAINT chk_machine_mem_usage
                             CHECK (mem_usage >= 0),

                         CONSTRAINT chk_machine_disk_usage
                             CHECK (disk_usage >= 0),

                         CONSTRAINT chk_machine_max_goroutines
                             CHECK (max_goroutines >= 0),

                         CONSTRAINT chk_machine_server_type
                             CHECK (server_type >= 0),

                         CONSTRAINT chk_machine_status
                             CHECK (status >= 0)
);

CREATE INDEX machine_region_ip_status_index
    ON machine (region, ip, status);

COMMENT ON TABLE machine IS '压力测试机器表';

COMMENT ON COLUMN machine.id IS '主键id';
COMMENT ON COLUMN machine.region IS '所属区域';
COMMENT ON COLUMN machine.ip IS '机器IP';
COMMENT ON COLUMN machine.port IS '端口';
COMMENT ON COLUMN machine.name IS '机器名称';
COMMENT ON COLUMN machine.cpu_usage IS 'CPU使用率';
COMMENT ON COLUMN machine.cpu_load_one IS 'CPU-1分钟内平均负载';
COMMENT ON COLUMN machine.cpu_load_five IS 'CPU-5分钟内平均负载';
COMMENT ON COLUMN machine.cpu_load_fifteen IS 'CPU-15分钟内平均负载';
COMMENT ON COLUMN machine.mem_usage IS '内存使用率';
COMMENT ON COLUMN machine.disk_usage IS '磁盘使用率';
COMMENT ON COLUMN machine.max_goroutines IS '最大协程数';
COMMENT ON COLUMN machine.current_goroutines IS '已用协程数';
COMMENT ON COLUMN machine.server_type IS '机器类型：1-主力机器，2-备用机器';
COMMENT ON COLUMN machine.status IS '机器状态：1-使用中，2-已卸载';
COMMENT ON COLUMN machine.created_at IS '创建时间';
COMMENT ON COLUMN machine.updated_at IS '修改时间';
COMMENT ON COLUMN machine.deleted_at IS '删除时间';

DROP TABLE IF EXISTS migrations;

CREATE TABLE migrations (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            version VARCHAR(50) NOT NULL,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            deleted_at TIMESTAMP DEFAULT NULL,

                            PRIMARY KEY (id)
);

COMMENT ON COLUMN migrations.id IS '主键id';
COMMENT ON COLUMN migrations.version IS '版本号';
COMMENT ON COLUMN migrations.created_at IS '创建时间';
COMMENT ON COLUMN migrations.updated_at IS '修改时间';
COMMENT ON COLUMN migrations.deleted_at IS '删除时间';

DROP TABLE IF EXISTS mock_target;

CREATE TABLE mock_target (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             target_id VARCHAR(100) NOT NULL,
                             team_id VARCHAR(100) NOT NULL,
                             target_type VARCHAR(10) NOT NULL,
                             name VARCHAR(255) NOT NULL,
                             parent_id VARCHAR(100) NOT NULL DEFAULT '0',
                             method VARCHAR(16) NOT NULL,
                             sort INTEGER NOT NULL DEFAULT 0,
                             type_sort INTEGER NOT NULL DEFAULT 0,
                             status SMALLINT NOT NULL DEFAULT 1,
                             version INTEGER NOT NULL DEFAULT 0,
                             created_user_id VARCHAR(100) NOT NULL,
                             recent_user_id VARCHAR(100) NOT NULL,
                             description TEXT NOT NULL,
                             source SMALLINT NOT NULL DEFAULT 0,
                             plan_id VARCHAR(100) NOT NULL,
                             source_id VARCHAR(100) NOT NULL,
                             is_checked SMALLINT NOT NULL DEFAULT 1,
                             is_disabled SMALLINT NOT NULL DEFAULT 0,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             deleted_at TIMESTAMP DEFAULT NULL,

                             PRIMARY KEY (id)
);

CREATE INDEX idx_target_id
    ON mock_target (target_id);

CREATE INDEX idx_plan_id
    ON mock_target (plan_id);

CREATE INDEX idx_team_id
    ON mock_target (team_id);

COMMENT ON TABLE mock_target IS '创建目标';

COMMENT ON COLUMN mock_target.id IS 'id';
COMMENT ON COLUMN mock_target.target_id IS '全局唯一ID';
COMMENT ON COLUMN mock_target.team_id IS '团队id';
COMMENT ON COLUMN mock_target.target_type IS '类型：文件夹，接口，分组，场景,测试用例';
COMMENT ON COLUMN mock_target.name IS '名称';
COMMENT ON COLUMN mock_target.parent_id IS '父级ID';
COMMENT ON COLUMN mock_target.method IS '方法';
COMMENT ON COLUMN mock_target.sort IS '排序';
COMMENT ON COLUMN mock_target.type_sort IS '类型排序';
COMMENT ON COLUMN mock_target.status IS '回收站状态：1-正常，2-回收站';
COMMENT ON COLUMN mock_target.version IS '产品版本号';
COMMENT ON COLUMN mock_target.created_user_id IS '创建人ID';
COMMENT ON COLUMN mock_target.recent_user_id IS '最近修改人ID';
COMMENT ON COLUMN mock_target.description IS '备注';
COMMENT ON COLUMN mock_target.source IS '数据来源：0-mock管理';
COMMENT ON COLUMN mock_target.plan_id IS '计划id';
COMMENT ON COLUMN mock_target.source_id IS '引用来源ID';
COMMENT ON COLUMN mock_target.is_checked IS '是否开启：1-开启，2-关闭';
COMMENT ON COLUMN mock_target.is_disabled IS '运行计划时是否禁用：0-不禁用，1-禁用';
COMMENT ON COLUMN mock_target.created_at IS '创建时间';
COMMENT ON COLUMN mock_target.updated_at IS '更新时间';
COMMENT ON COLUMN mock_target.deleted_at IS '删除时间';

DROP TABLE IF EXISTS mock_target_debug_log;

CREATE TABLE mock_target_debug_log (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       target_id VARCHAR(100) NOT NULL,
                                       target_type SMALLINT NOT NULL,
                                       team_id VARCHAR(100) NOT NULL,
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       deleted_at TIMESTAMP DEFAULT NULL,

                                       PRIMARY KEY (id)
);

CREATE INDEX idx_target_id
    ON mock_target_debug_log (target_id);

COMMENT ON TABLE mock_target_debug_log IS 'mock目标调试日志表';

COMMENT ON COLUMN mock_target_debug_log.id IS '主键ID';
COMMENT ON COLUMN mock_target_debug_log.target_id IS '目标唯一ID';
COMMENT ON COLUMN mock_target_debug_log.target_type IS '目标类型：1-api，2-scene';
COMMENT ON COLUMN mock_target_debug_log.team_id IS '团队ID';
COMMENT ON COLUMN mock_target_debug_log.created_at IS '创建时间';
COMMENT ON COLUMN mock_target_debug_log.updated_at IS '更新时间';
COMMENT ON COLUMN mock_target_debug_log.deleted_at IS '删除时间';


DROP TABLE IF EXISTS permission;

CREATE TABLE permission (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            permission_id BIGINT NOT NULL DEFAULT 0,
                            title VARCHAR(100) NOT NULL DEFAULT '',
                            mark VARCHAR(100) NOT NULL DEFAULT '',
                            url VARCHAR(100) NOT NULL DEFAULT '',
                            type SMALLINT NOT NULL DEFAULT 0,
                            group_id INTEGER NOT NULL DEFAULT 0,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            deleted_at TIMESTAMP DEFAULT NULL,

                            PRIMARY KEY (id)
);

COMMENT ON TABLE permission IS '权限表';

COMMENT ON COLUMN permission.id IS '主键id';
COMMENT ON COLUMN permission.permission_id IS '权限ID';
COMMENT ON COLUMN permission.title IS '权限内容';
COMMENT ON COLUMN permission.mark IS '权限标识';
COMMENT ON COLUMN permission.url IS '权限url';
COMMENT ON COLUMN permission.type IS '类型（1：权限   2：功能）';
COMMENT ON COLUMN permission.group_id IS '所属权限组（1：企业成员管理  2：团队管理  3：角色管理）';


DROP TABLE IF EXISTS preinstall_conf;

CREATE TABLE preinstall_conf (
                                 id BIGSERIAL PRIMARY KEY,
                                 conf_name VARCHAR(100) NOT NULL,
                                 team_id VARCHAR(100) NOT NULL,
                                 user_id VARCHAR(100) NOT NULL DEFAULT '0',
                                 user_name VARCHAR(64) NOT NULL,
                                 task_type SMALLINT NOT NULL DEFAULT 0,
                                 task_mode SMALLINT NOT NULL DEFAULT 0,
                                 control_mode SMALLINT NOT NULL DEFAULT 0,
                                 debug_mode VARCHAR(100) NOT NULL DEFAULT 'stop',
                                 mode_conf TEXT NOT NULL,
                                 timed_task_conf TEXT NOT NULL,
                                 is_open_distributed SMALLINT NOT NULL DEFAULT 0,
                                 machine_dispatch_mode_conf TEXT NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 deleted_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE preinstall_conf IS '预设配置表';

COMMENT ON COLUMN preinstall_conf.id IS '主键id';
COMMENT ON COLUMN preinstall_conf.conf_name IS '配置名称';
COMMENT ON COLUMN preinstall_conf.team_id IS '团队ID';
COMMENT ON COLUMN preinstall_conf.user_id IS '用户ID';
COMMENT ON COLUMN preinstall_conf.user_name IS '用户名称';
COMMENT ON COLUMN preinstall_conf.task_type IS '任务类型';
COMMENT ON COLUMN preinstall_conf.task_mode IS '压测模式';
COMMENT ON COLUMN preinstall_conf.control_mode IS '控制模式：0-集中模式，1-单独模式';
COMMENT ON COLUMN preinstall_conf.debug_mode IS 'debug模式：stop-关闭，all-开启全部日志，only_success-开启仅成功日志，only_error-开启仅错误日志';
COMMENT ON COLUMN preinstall_conf.mode_conf IS '压测配置详情';
COMMENT ON COLUMN preinstall_conf.timed_task_conf IS '定时任务相关配置';
COMMENT ON COLUMN preinstall_conf.is_open_distributed IS '是否开启分布式调度：0-关闭，1-开启';
COMMENT ON COLUMN preinstall_conf.machine_dispatch_mode_conf IS '分布式压力机配置';
COMMENT ON COLUMN preinstall_conf.created_at IS '创建时间';
COMMENT ON COLUMN preinstall_conf.updated_at IS '更新时间';
COMMENT ON COLUMN preinstall_conf.deleted_at IS '删除时间';

CREATE INDEX idx_preinstall_conf_team_id
    ON preinstall_conf (team_id);

DROP TABLE IF EXISTS public_function;

CREATE TABLE public_function (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 function VARCHAR(255) NOT NULL,
                                 function_name VARCHAR(255) NOT NULL,
                                 remark TEXT NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 deleted_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE public_function IS '公共函数表';

COMMENT ON COLUMN public_function.id IS '主键id';
COMMENT ON COLUMN public_function.function IS '函数';
COMMENT ON COLUMN public_function.function_name IS '函数名称';
COMMENT ON COLUMN public_function.remark IS '备注';
COMMENT ON COLUMN public_function.created_at IS '创建时间';
COMMENT ON COLUMN public_function.updated_at IS '修改时间';
COMMENT ON COLUMN public_function.deleted_at IS '删除时间';


DROP TABLE IF EXISTS migrations;

CREATE TABLE migrations (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            version VARCHAR(50) NOT NULL,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            deleted_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE migrations IS '数据库迁移记录表';

COMMENT ON COLUMN migrations.id IS '主键id';
COMMENT ON COLUMN migrations.version IS '版本号';
COMMENT ON COLUMN migrations.created_at IS '创建时间';
COMMENT ON COLUMN migrations.updated_at IS '修改时间';
COMMENT ON COLUMN migrations.deleted_at IS '删除时间';

DROP TABLE IF EXISTS report_machine;

CREATE TABLE report_machine (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                report_id VARCHAR(100) NOT NULL,
                                plan_id VARCHAR(100) NOT NULL DEFAULT '0',
                                team_id VARCHAR(100) NOT NULL,
                                ip VARCHAR(15) NOT NULL,
                                concurrency BIGINT NOT NULL DEFAULT 0,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_report_machine_report_id
    ON report_machine (report_id);

COMMENT ON TABLE report_machine IS '报告压力机表';

COMMENT ON COLUMN report_machine.id IS '主键ID';
COMMENT ON COLUMN report_machine.report_id IS '报告id';
COMMENT ON COLUMN report_machine.plan_id IS '计划ID';
COMMENT ON COLUMN report_machine.team_id IS '团队ID';
COMMENT ON COLUMN report_machine.ip IS '机器ip';
COMMENT ON COLUMN report_machine.concurrency IS '并发数';
COMMENT ON COLUMN report_machine.created_at IS '创建时间';
COMMENT ON COLUMN report_machine.updated_at IS '更新时间';
COMMENT ON COLUMN report_machine.deleted_at IS '删除时间';

DROP TABLE IF EXISTS role;

CREATE TABLE role (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      role_id VARCHAR(100) NOT NULL,
                      role_type SMALLINT NOT NULL DEFAULT 0,
                      name VARCHAR(100) NOT NULL DEFAULT '',
                      company_id VARCHAR(100) NOT NULL DEFAULT '',
                      level SMALLINT NOT NULL DEFAULT 0,
                      is_default SMALLINT NOT NULL DEFAULT 2,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_role_id
    ON role (role_id);

COMMENT ON TABLE role IS '角色表';

COMMENT ON COLUMN role.id IS '主键id';
COMMENT ON COLUMN role.role_id IS '角色id';
COMMENT ON COLUMN role.role_type IS '角色分类（1：企业  2：团队）';
COMMENT ON COLUMN role.name IS '角色名称';
COMMENT ON COLUMN role.company_id IS '企业id';
COMMENT ON COLUMN role.level IS '角色层级（1:超管/团队管理员 2:管理员/团队成员 3:普通成员/只读成员/自定义角色）';
COMMENT ON COLUMN role.is_default IS '是否是默认角色 1：是 2：自定义角色';
COMMENT ON COLUMN role.created_at IS '创建时间';
COMMENT ON COLUMN role.updated_at IS '更新时间';
COMMENT ON COLUMN role.deleted_at IS '删除时间';

DROP TABLE IF EXISTS role_permission;

CREATE TABLE role_permission (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 role_id VARCHAR(100) NOT NULL,
                                 permission_id BIGINT NOT NULL DEFAULT 0,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_role_permission_role_id
    ON role_permission (role_id);

COMMENT ON TABLE role_permission IS '角色权限表';

COMMENT ON COLUMN role_permission.id IS '主键id';
COMMENT ON COLUMN role_permission.role_id IS '角色id';
COMMENT ON COLUMN role_permission.permission_id IS '权限id';
COMMENT ON COLUMN role_permission.created_at IS '创建时间';
COMMENT ON COLUMN role_permission.updated_at IS '更新时间';
COMMENT ON COLUMN role_permission.deleted_at IS '删除时间';

DROP TABLE IF EXISTS role_type_permission;

CREATE TABLE role_type_permission (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      role_type SMALLINT NOT NULL DEFAULT 0,
                                      permission_id BIGINT NOT NULL DEFAULT 0,
                                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      deleted_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE role_type_permission IS '角色分类可拥有的权限';

COMMENT ON COLUMN role_type_permission.id IS '主键id';
COMMENT ON COLUMN role_type_permission.role_type IS '角色分类（1：企业  2：团队）';
COMMENT ON COLUMN role_type_permission.permission_id IS '权限id';
COMMENT ON COLUMN role_type_permission.created_at IS '创建时间';
COMMENT ON COLUMN role_type_permission.updated_at IS '更新时间';
COMMENT ON COLUMN role_type_permission.deleted_at IS '删除时间';

DROP TABLE IF EXISTS scene_variable;

CREATE TABLE scene_variable (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                team_id VARCHAR(100) NOT NULL,
                                scene_id VARCHAR(100) NOT NULL,
                                type SMALLINT NOT NULL DEFAULT 0,
                                var VARCHAR(255) NOT NULL,
                                val TEXT NOT NULL,
                                description TEXT NOT NULL,
                                status SMALLINT NOT NULL DEFAULT 1,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_scene_variable_team_id
    ON scene_variable (team_id);

CREATE INDEX idx_scene_variable_scene_id
    ON scene_variable (scene_id);

COMMENT ON TABLE scene_variable IS '设置变量表';

COMMENT ON COLUMN scene_variable.id IS '主键id';
COMMENT ON COLUMN scene_variable.team_id IS '团队id';
COMMENT ON COLUMN scene_variable.scene_id IS '场景ID';
COMMENT ON COLUMN scene_variable.type IS '使用范围：1-全局变量，2-场景变量';
COMMENT ON COLUMN scene_variable.var IS '变量名';
COMMENT ON COLUMN scene_variable.val IS '变量值';
COMMENT ON COLUMN scene_variable.description IS '描述';
COMMENT ON COLUMN scene_variable.status IS '开关状态：1-开启，2-关闭';
COMMENT ON COLUMN scene_variable.created_at IS '创建时间';
COMMENT ON COLUMN scene_variable.updated_at IS '修改时间';
COMMENT ON COLUMN scene_variable.deleted_at IS '删除时间';

DROP TABLE IF EXISTS setting;

CREATE TABLE setting (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id VARCHAR(100) NOT NULL,
                         team_id VARCHAR(100) NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_setting_user_id
    ON setting (user_id);

COMMENT ON TABLE setting IS '设置表';

COMMENT ON COLUMN setting.id IS '主键id';
COMMENT ON COLUMN setting.user_id IS '用户id';
COMMENT ON COLUMN setting.team_id IS '当前团队id';
COMMENT ON COLUMN setting.created_at IS '创建时间';
COMMENT ON COLUMN setting.updated_at IS '更新时间';
COMMENT ON COLUMN setting.deleted_at IS '删除时间';


DROP TABLE IF EXISTS sms_log;

CREATE TABLE sms_log (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         type SMALLINT NOT NULL,
                         mobile CHAR(11) NOT NULL DEFAULT '',
                         content VARCHAR(200) NOT NULL,
                         verify_code VARCHAR(20) NOT NULL,
                         verify_code_expiration_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         client_ip VARCHAR(100) NOT NULL DEFAULT '',
                         send_status SMALLINT NOT NULL DEFAULT 1,
                         verify_status SMALLINT NOT NULL DEFAULT 1,
                         send_response TEXT NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_sms_log_type_mobile_verify_code
    ON sms_log (
                type,
                mobile,
                verify_code,
                verify_code_expiration_time
        );

COMMENT ON TABLE sms_log IS '短信发送记录表';

COMMENT ON COLUMN sms_log.id IS '主键id';
COMMENT ON COLUMN sms_log.type IS '短信类型: 1-注册，2-登录，3-找回密码';
COMMENT ON COLUMN sms_log.mobile IS '手机号';
COMMENT ON COLUMN sms_log.content IS '短信内容';
COMMENT ON COLUMN sms_log.verify_code IS '验证码';
COMMENT ON COLUMN sms_log.verify_code_expiration_time IS '验证码有效时间';
COMMENT ON COLUMN sms_log.client_ip IS '客户端IP';
COMMENT ON COLUMN sms_log.send_status IS '发送状态：1-成功 2-失败';
COMMENT ON COLUMN sms_log.verify_status IS '校验状态：1-未校验 2-已校验';
COMMENT ON COLUMN sms_log.send_response IS '短信服务响应';
COMMENT ON COLUMN sms_log.created_at IS '创建时间';
COMMENT ON COLUMN sms_log.updated_at IS '修改时间';
COMMENT ON COLUMN sms_log.deleted_at IS '删除时间';

DROP TABLE IF EXISTS stress_plan;

CREATE TABLE stress_plan (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             plan_id VARCHAR(100) NOT NULL DEFAULT '0',
                             team_id VARCHAR(100) NOT NULL,
                             rank_id BIGINT NOT NULL DEFAULT 0,
                             plan_name VARCHAR(255) NOT NULL,
                             task_type SMALLINT NOT NULL DEFAULT 0,
                             task_mode SMALLINT NOT NULL DEFAULT 0,
                             status SMALLINT NOT NULL DEFAULT 1,
                             create_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                             run_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                             remark TEXT NOT NULL,
                             run_count BIGINT NOT NULL DEFAULT 0,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_stress_plan_plan_id
    ON stress_plan (plan_id);

CREATE INDEX idx_stress_plan_team_id
    ON stress_plan (team_id);

COMMENT ON TABLE stress_plan IS '性能计划表';

COMMENT ON COLUMN stress_plan.id IS '主键ID';
COMMENT ON COLUMN stress_plan.plan_id IS '计划ID';
COMMENT ON COLUMN stress_plan.team_id IS '团队ID';
COMMENT ON COLUMN stress_plan.rank_id IS '序号ID';
COMMENT ON COLUMN stress_plan.plan_name IS '计划名称';
COMMENT ON COLUMN stress_plan.task_type IS '计划类型：1-普通任务，2-定时任务';
COMMENT ON COLUMN stress_plan.task_mode IS '压测类型: 1-并发模式，2-阶梯模式，3-错误率模式，4-响应时间模式，5-每秒请求数模式，6-每秒事务数模式';
COMMENT ON COLUMN stress_plan.status IS '计划状态1:未开始,2:进行中';
COMMENT ON COLUMN stress_plan.create_user_id IS '创建人id';
COMMENT ON COLUMN stress_plan.run_user_id IS '运行人id';
COMMENT ON COLUMN stress_plan.remark IS '备注';
COMMENT ON COLUMN stress_plan.run_count IS '运行次数';
COMMENT ON COLUMN stress_plan.created_at IS '创建时间';
COMMENT ON COLUMN stress_plan.updated_at IS '修改时间';
COMMENT ON COLUMN stress_plan.deleted_at IS '删除时间';


DROP TABLE IF EXISTS stress_plan_email;

CREATE TABLE stress_plan_email (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   plan_id VARCHAR(100) NOT NULL,
                                   team_id VARCHAR(100) NOT NULL,
                                   email VARCHAR(255) DEFAULT NULL,
                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_stress_plan_email_plan_id
    ON stress_plan_email (plan_id);

COMMENT ON TABLE stress_plan_email IS '性能计划收件人';

COMMENT ON COLUMN stress_plan_email.id IS '主键';
COMMENT ON COLUMN stress_plan_email.plan_id IS '计划ID';
COMMENT ON COLUMN stress_plan_email.team_id IS '团队ID';
COMMENT ON COLUMN stress_plan_email.email IS '邮箱';
COMMENT ON COLUMN stress_plan_email.created_at IS '创建时间';
COMMENT ON COLUMN stress_plan_email.updated_at IS '更新时间';
COMMENT ON COLUMN stress_plan_email.deleted_at IS '删除时间';

DROP TABLE IF EXISTS stress_plan_report;

CREATE TABLE stress_plan_report (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    report_id VARCHAR(100) NOT NULL,
                                    report_name VARCHAR(125) NOT NULL,
                                    team_id VARCHAR(100) NOT NULL,
                                    plan_id VARCHAR(100) NOT NULL,
                                    rank_id BIGINT NOT NULL DEFAULT 0,
                                    plan_name VARCHAR(255) NOT NULL,
                                    scene_id VARCHAR(100) NOT NULL,
                                    scene_name VARCHAR(255) NOT NULL,
                                    task_type INTEGER NOT NULL,
                                    task_mode INTEGER NOT NULL,
                                    control_mode SMALLINT NOT NULL DEFAULT 0,
                                    debug_mode VARCHAR(100) NOT NULL DEFAULT 'stop',
                                    run_duration_time BIGINT NOT NULL DEFAULT 0,
                                    status SMALLINT NOT NULL,
                                    remark TEXT NOT NULL,
                                    run_user_id VARCHAR(100) NOT NULL,
                                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_stress_plan_report_report_id
    ON stress_plan_report (report_id);

CREATE INDEX idx_stress_plan_report_team_id
    ON stress_plan_report (team_id);

COMMENT ON TABLE stress_plan_report IS '性能测试报告表';

COMMENT ON COLUMN stress_plan_report.id IS '主键ID';
COMMENT ON COLUMN stress_plan_report.report_id IS '报告ID';
COMMENT ON COLUMN stress_plan_report.report_name IS '报告名称';
COMMENT ON COLUMN stress_plan_report.team_id IS '团队ID';
COMMENT ON COLUMN stress_plan_report.plan_id IS '计划ID';
COMMENT ON COLUMN stress_plan_report.rank_id IS '序号ID';
COMMENT ON COLUMN stress_plan_report.plan_name IS '计划名称';
COMMENT ON COLUMN stress_plan_report.scene_id IS '场景ID';
COMMENT ON COLUMN stress_plan_report.scene_name IS '场景名称';
COMMENT ON COLUMN stress_plan_report.task_type IS '任务类型';
COMMENT ON COLUMN stress_plan_report.task_mode IS '压测模式';
COMMENT ON COLUMN stress_plan_report.control_mode IS '控制模式：0-集中模式，1-单独模式';
COMMENT ON COLUMN stress_plan_report.debug_mode IS 'debug模式：stop-关闭，all-开启全部日志，only_success-开启仅成功日志，only_error-开启仅错误日志';
COMMENT ON COLUMN stress_plan_report.run_duration_time IS '任务运行持续时长';
COMMENT ON COLUMN stress_plan_report.status IS '报告状态1:进行中，2:已完成';
COMMENT ON COLUMN stress_plan_report.remark IS '备注';
COMMENT ON COLUMN stress_plan_report.run_user_id IS '启动人id';
COMMENT ON COLUMN stress_plan_report.created_at IS '创建时间（执行时间）';
COMMENT ON COLUMN stress_plan_report.updated_at IS '更新时间';
COMMENT ON COLUMN stress_plan_report.deleted_at IS '删除时间';



DROP TABLE IF EXISTS stress_plan_task_conf;

CREATE TABLE stress_plan_task_conf (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       plan_id VARCHAR(100) NOT NULL DEFAULT '0',
                                       team_id VARCHAR(100) NOT NULL,
                                       scene_id VARCHAR(100) NOT NULL,
                                       task_type SMALLINT NOT NULL DEFAULT 0,
                                       task_mode SMALLINT NOT NULL DEFAULT 0,
                                       control_mode SMALLINT NOT NULL DEFAULT 0,
                                       debug_mode VARCHAR(100) NOT NULL DEFAULT 'stop',
                                       mode_conf TEXT NOT NULL,
                                       is_open_distributed SMALLINT NOT NULL DEFAULT 0,
                                       machine_dispatch_mode_conf TEXT NOT NULL,
                                       run_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_stress_plan_task_conf_plan_id
    ON stress_plan_task_conf (plan_id);

CREATE INDEX idx_stress_plan_task_conf_scene_id
    ON stress_plan_task_conf (scene_id);

COMMENT ON TABLE stress_plan_task_conf IS '性能计划—普通任务配置表';

COMMENT ON COLUMN stress_plan_task_conf.id IS '配置ID';
COMMENT ON COLUMN stress_plan_task_conf.plan_id IS '计划ID';
COMMENT ON COLUMN stress_plan_task_conf.team_id IS '团队ID';
COMMENT ON COLUMN stress_plan_task_conf.scene_id IS '场景ID';
COMMENT ON COLUMN stress_plan_task_conf.task_type IS '任务类型：1-普通模式，2-定时任务';
COMMENT ON COLUMN stress_plan_task_conf.task_mode IS '压测模式：1-并发模式，2-阶梯模式，3-错误率模式，4-响应时间模式，5-每秒请求数模式，6-每秒事务数模式';
COMMENT ON COLUMN stress_plan_task_conf.control_mode IS '控制模式：0-集中模式，1-单独模式';
COMMENT ON COLUMN stress_plan_task_conf.debug_mode IS 'debug模式：stop-关闭，all-开启全部日志，only_success-开启仅成功日志，only_error-开启仅错误日志';
COMMENT ON COLUMN stress_plan_task_conf.mode_conf IS '压测模式配置详情';
COMMENT ON COLUMN stress_plan_task_conf.is_open_distributed IS '是否开启分布式调度：0-关闭，1-开启';
COMMENT ON COLUMN stress_plan_task_conf.machine_dispatch_mode_conf IS '分布式压力机配置';
COMMENT ON COLUMN stress_plan_task_conf.run_user_id IS '运行人用户ID';
COMMENT ON COLUMN stress_plan_task_conf.created_at IS '创建时间';
COMMENT ON COLUMN stress_plan_task_conf.updated_at IS '更新时间';
COMMENT ON COLUMN stress_plan_task_conf.deleted_at IS '删除时间';

DROP TABLE IF EXISTS stress_plan_timed_task_conf;

CREATE TABLE stress_plan_timed_task_conf (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             plan_id VARCHAR(100) NOT NULL,
                                             scene_id VARCHAR(100) NOT NULL,
                                             team_id VARCHAR(100) NOT NULL,
                                             user_id VARCHAR(100) NOT NULL,
                                             frequency INTEGER NOT NULL DEFAULT 0,
                                             task_exec_time BIGINT NOT NULL DEFAULT 0,
                                             task_close_time BIGINT NOT NULL DEFAULT 0,
                                             task_type SMALLINT NOT NULL DEFAULT 2,
                                             task_mode SMALLINT NOT NULL DEFAULT 1,
                                             control_mode SMALLINT NOT NULL DEFAULT 0,
                                             debug_mode VARCHAR(100) NOT NULL DEFAULT 'stop',
                                             mode_conf TEXT NOT NULL,
                                             is_open_distributed SMALLINT NOT NULL DEFAULT 0,
                                             machine_dispatch_mode_conf TEXT NOT NULL,
                                             run_user_id VARCHAR(100) NOT NULL DEFAULT '0',
                                             status SMALLINT NOT NULL DEFAULT 0,
                                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_stress_plan_timed_task_conf_plan_id
    ON stress_plan_timed_task_conf (plan_id);

CREATE INDEX idx_stress_plan_timed_task_conf_scene_id
    ON stress_plan_timed_task_conf (scene_id);

COMMENT ON TABLE stress_plan_timed_task_conf IS '性能计划-定时任务配置表';

COMMENT ON COLUMN stress_plan_timed_task_conf.id IS '表id';
COMMENT ON COLUMN stress_plan_timed_task_conf.plan_id IS '计划id';
COMMENT ON COLUMN stress_plan_timed_task_conf.scene_id IS '场景id';
COMMENT ON COLUMN stress_plan_timed_task_conf.team_id IS '团队id';
COMMENT ON COLUMN stress_plan_timed_task_conf.user_id IS '用户ID';
COMMENT ON COLUMN stress_plan_timed_task_conf.frequency IS '任务执行频次: 0-一次，1-每天，2-每周，3-每月';
COMMENT ON COLUMN stress_plan_timed_task_conf.task_exec_time IS '任务执行时间';
COMMENT ON COLUMN stress_plan_timed_task_conf.task_close_time IS '任务结束时间';
COMMENT ON COLUMN stress_plan_timed_task_conf.task_type IS '任务类型：1-普通任务，2-定时任务';
COMMENT ON COLUMN stress_plan_timed_task_conf.task_mode IS '压测模式：1-并发模式，2-阶梯模式，3-错误率模式，4-响应时间模式，5-每秒请求数模式，6 -每秒事务数模式';
COMMENT ON COLUMN stress_plan_timed_task_conf.control_mode IS '控制模式：0-集中模式，1-单独模式';
COMMENT ON COLUMN stress_plan_timed_task_conf.debug_mode IS 'debug模式：stop-关闭，all-开启全部日志，only_success-开启仅成功日志，only_error-开启仅错误日志';
COMMENT ON COLUMN stress_plan_timed_task_conf.mode_conf IS '压测详细配置';
COMMENT ON COLUMN stress_plan_timed_task_conf.is_open_distributed IS '是否开启分布式调度：0-关闭，1-开启';
COMMENT ON COLUMN stress_plan_timed_task_conf.machine_dispatch_mode_conf IS '分布式压力机配置';
COMMENT ON COLUMN stress_plan_timed_task_conf.run_user_id IS '运行人ID';
COMMENT ON COLUMN stress_plan_timed_task_conf.status IS '任务状态：0-未启用，1-运行中，2-已过期';
COMMENT ON COLUMN stress_plan_timed_task_conf.created_at IS '创建时间';
COMMENT ON COLUMN stress_plan_timed_task_conf.updated_at IS '更新时间';
COMMENT ON COLUMN stress_plan_timed_task_conf.deleted_at IS '删除时间';


DROP TABLE IF EXISTS target;

CREATE TABLE target (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        target_id VARCHAR(100) NOT NULL,
                        team_id VARCHAR(100) NOT NULL,
                        target_type VARCHAR(10) NOT NULL,
                        name VARCHAR(255) NOT NULL,
                        parent_id VARCHAR(100) NOT NULL DEFAULT '0',
                        method VARCHAR(16) NOT NULL,
                        sort INTEGER NOT NULL DEFAULT 0,
                        type_sort INTEGER NOT NULL DEFAULT 0,
                        status SMALLINT NOT NULL DEFAULT 1,
                        version INTEGER NOT NULL DEFAULT 0,
                        created_user_id VARCHAR(100) NOT NULL,
                        recent_user_id VARCHAR(100) NOT NULL,
                        description TEXT NOT NULL,
                        source SMALLINT NOT NULL DEFAULT 0,
                        plan_id VARCHAR(100) NOT NULL,
                        source_id VARCHAR(100) NOT NULL,
                        is_checked SMALLINT NOT NULL DEFAULT 1,
                        is_disabled SMALLINT NOT NULL DEFAULT 0,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_target_target_id
    ON target (target_id);

CREATE INDEX idx_target_plan_id
    ON target (plan_id);

CREATE INDEX idx_target_team_id
    ON target (team_id);

COMMENT ON TABLE target IS '创建目标';

COMMENT ON COLUMN target.id IS 'id';
COMMENT ON COLUMN target.target_id IS '全局唯一ID';
COMMENT ON COLUMN target.team_id IS '团队id';
COMMENT ON COLUMN target.target_type IS '类型：文件夹，接口，分组，场景,测试用例';
COMMENT ON COLUMN target.name IS '名称';
COMMENT ON COLUMN target.parent_id IS '父级ID';
COMMENT ON COLUMN target.method IS '方法';
COMMENT ON COLUMN target.sort IS '排序';
COMMENT ON COLUMN target.type_sort IS '类型排序';
COMMENT ON COLUMN target.status IS '回收站状态：1-正常，2-回收站';
COMMENT ON COLUMN target.version IS '产品版本号';
COMMENT ON COLUMN target.created_user_id IS '创建人ID';
COMMENT ON COLUMN target.recent_user_id IS '最近修改人ID';
COMMENT ON COLUMN target.description IS '备注';
COMMENT ON COLUMN target.source IS '数据来源：0-测试对象，1-场景管理，2-性能，3-自动化测试，4-mock';
COMMENT ON COLUMN target.plan_id IS '计划id';
COMMENT ON COLUMN target.source_id IS '引用来源ID';
COMMENT ON COLUMN target.is_checked IS '是否开启：1-开启，2-关闭';
COMMENT ON COLUMN target.is_disabled IS '运行计划时是否禁用：0-不禁用，1-禁用';
COMMENT ON COLUMN target.created_at IS '创建时间';
COMMENT ON COLUMN target.updated_at IS '更新时间';
COMMENT ON COLUMN target.deleted_at IS '删除时间';

DROP TABLE IF EXISTS target_debug_log;

CREATE TABLE target_debug_log (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  target_id VARCHAR(100) NOT NULL,
                                  target_type SMALLINT NOT NULL,
                                  team_id VARCHAR(100) NOT NULL,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_target_debug_log_target_id
    ON target_debug_log (target_id);

COMMENT ON TABLE target_debug_log IS '目标调试日志表';

COMMENT ON COLUMN target_debug_log.id IS '主键ID';
COMMENT ON COLUMN target_debug_log.target_id IS '目标唯一ID';
COMMENT ON COLUMN target_debug_log.target_type IS '目标类型：1-api，2-scene';
COMMENT ON COLUMN target_debug_log.team_id IS '团队ID';
COMMENT ON COLUMN target_debug_log.created_at IS '创建时间';
COMMENT ON COLUMN target_debug_log.updated_at IS '更新时间';
COMMENT ON COLUMN target_debug_log.deleted_at IS '删除时间';

DROP TABLE IF EXISTS team;

CREATE TABLE team (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      team_id VARCHAR(100) NOT NULL,
                      name VARCHAR(64) NOT NULL,
                      description TEXT,
                      company_id VARCHAR(100) NOT NULL DEFAULT '',
                      type SMALLINT NOT NULL,
                      trial_expiration_date TIMESTAMP NOT NULL,
                      is_vip SMALLINT NOT NULL DEFAULT 1,
                      vip_expiration_date TIMESTAMP NOT NULL,
                      vum_num BIGINT NOT NULL DEFAULT 0,
                      max_user_num BIGINT NOT NULL DEFAULT 0,
                      created_user_id VARCHAR(100) NOT NULL,
                      team_buy_version_type INTEGER NOT NULL DEFAULT 1,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_team_team_id
    ON team (team_id);

COMMENT ON TABLE team IS '团队表';

COMMENT ON COLUMN team.id IS '主键ID';
COMMENT ON COLUMN team.team_id IS '团队ID';
COMMENT ON COLUMN team.name IS '团队名称';
COMMENT ON COLUMN team.description IS '团队描述';
COMMENT ON COLUMN team.company_id IS '所属企业id';
COMMENT ON COLUMN team.type IS '团队类型 1: 私有团队；2: 普通团队';
COMMENT ON COLUMN team.trial_expiration_date IS '试用有效期';
COMMENT ON COLUMN team.is_vip IS '是否为付费团队 1-否 2-是';
COMMENT ON COLUMN team.vip_expiration_date IS '付费有效期';
COMMENT ON COLUMN team.vum_num IS '当前可用VUM总数';
COMMENT ON COLUMN team.max_user_num IS '当前团队最大成员数量';
COMMENT ON COLUMN team.created_user_id IS '创建者id';
COMMENT ON COLUMN team.team_buy_version_type IS '团队套餐类型：1-个人版，2-团队版，3-企业版，4-私有化部署';
COMMENT ON COLUMN team.created_at IS '创建时间';
COMMENT ON COLUMN team.updated_at IS '更新时间';
COMMENT ON COLUMN team.deleted_at IS '删除时间';


DROP TABLE IF EXISTS team_env;

CREATE TABLE team_env (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          team_id VARCHAR(100) NOT NULL,
                          name VARCHAR(100) NOT NULL,
                          created_user_id VARCHAR(100) NOT NULL,
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_team_env_team_id
    ON team_env (team_id);

COMMENT ON TABLE team_env IS '环境管理表';

COMMENT ON COLUMN team_env.id IS '主键id';
COMMENT ON COLUMN team_env.team_id IS '团队id';
COMMENT ON COLUMN team_env.name IS '环境名称';
COMMENT ON COLUMN team_env.created_user_id IS '创建人id';
COMMENT ON COLUMN team_env.created_at IS '创建时间';
COMMENT ON COLUMN team_env.updated_at IS '修改时间';
COMMENT ON COLUMN team_env.deleted_at IS '删除时间';

DROP TABLE IF EXISTS team_env_database;

CREATE TABLE team_env_database (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   team_id VARCHAR(100) NOT NULL,
                                   team_env_id BIGINT NOT NULL,
                                   type VARCHAR(100) NOT NULL,
                                   server_name VARCHAR(100) NOT NULL,
                                   host VARCHAR(200) NOT NULL,
                                   port INTEGER NOT NULL,
                                   "user" VARCHAR(100) NOT NULL,
                                   password VARCHAR(200) NOT NULL,
                                   db_name VARCHAR(100) NOT NULL,
                                   charset VARCHAR(100) NOT NULL DEFAULT 'utf8mb4',
                                   created_user_id VARCHAR(100) NOT NULL,
                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_team_env_database_team_id
    ON team_env_database (team_id);

CREATE INDEX idx_team_env_database_team_env_id
    ON team_env_database (team_env_id);

COMMENT ON TABLE team_env_database IS 'Sql数据库服务基础信息表';

COMMENT ON COLUMN team_env_database.id IS '主键id';
COMMENT ON COLUMN team_env_database.team_id IS '团队id';
COMMENT ON COLUMN team_env_database.team_env_id IS '环境变量id';
COMMENT ON COLUMN team_env_database.type IS '数据库类型';
COMMENT ON COLUMN team_env_database.server_name IS 'mysql服务名称';
COMMENT ON COLUMN team_env_database.host IS '服务地址';
COMMENT ON COLUMN team_env_database.port IS '端口号';
COMMENT ON COLUMN team_env_database."user" IS '账号';
COMMENT ON COLUMN team_env_database.password IS '密码';
COMMENT ON COLUMN team_env_database.db_name IS '数据库名称';
COMMENT ON COLUMN team_env_database.charset IS '字符编码集';
COMMENT ON COLUMN team_env_database.created_user_id IS '创建人id';
COMMENT ON COLUMN team_env_database.created_at IS '创建时间';
COMMENT ON COLUMN team_env_database.updated_at IS '更新时间';
COMMENT ON COLUMN team_env_database.deleted_at IS '删除时间';

DROP TABLE IF EXISTS team_env_service;

CREATE TABLE team_env_service (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  team_id VARCHAR(100) NOT NULL,
                                  team_env_id BIGINT NOT NULL DEFAULT 0,
                                  name VARCHAR(100) NOT NULL,
                                  content VARCHAR(200) NOT NULL,
                                  created_user_id VARCHAR(100) NOT NULL,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idxx_team_id
    ON team_env_service (team_id);

COMMENT ON TABLE team_env_service IS '团队环境服务管理';

COMMENT ON COLUMN team_env_service.id IS '主键id';
COMMENT ON COLUMN team_env_service.team_id IS '团队id';
COMMENT ON COLUMN team_env_service.team_env_id IS '环境id';
COMMENT ON COLUMN team_env_service.name IS '服务名称';
COMMENT ON COLUMN team_env_service.content IS '服务URL';
COMMENT ON COLUMN team_env_service.created_user_id IS '创建人id';
COMMENT ON COLUMN team_env_service.created_at IS '创建时间';
COMMENT ON COLUMN team_env_service.updated_at IS '更新时间';
COMMENT ON COLUMN team_env_service.deleted_at IS '删除时间';

DROP TABLE IF EXISTS team_user_queue;

CREATE TABLE team_user_queue (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 email VARCHAR(255) NOT NULL,
                                 team_id VARCHAR(100) NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_team_user_queue_team_id
    ON team_user_queue (team_id);

COMMENT ON TABLE team_user_queue IS '邀请待注册队列';

COMMENT ON COLUMN team_user_queue.id IS '主键id';
COMMENT ON COLUMN team_user_queue.email IS '邮箱';
COMMENT ON COLUMN team_user_queue.team_id IS '团队id';
COMMENT ON COLUMN team_user_queue.created_at IS '创建时间';
COMMENT ON COLUMN team_user_queue.updated_at IS '更新时间';
COMMENT ON COLUMN team_user_queue.deleted_at IS '删除时间';

DROP TABLE IF EXISTS third_notice;

CREATE TABLE third_notice (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              notice_id VARCHAR(100) NOT NULL,
                              name VARCHAR(100) NOT NULL DEFAULT '',
                              channel_id BIGINT NOT NULL DEFAULT 0,
                              params JSONB DEFAULT NULL,
                              status SMALLINT NOT NULL DEFAULT 1,
                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_third_notice_notice_id
    ON third_notice (notice_id);

COMMENT ON TABLE third_notice IS '三方通知设置';

COMMENT ON COLUMN third_notice.id IS '主键id';
COMMENT ON COLUMN third_notice.notice_id IS '通知id';
COMMENT ON COLUMN third_notice.name IS '通知名称';
COMMENT ON COLUMN third_notice.channel_id IS '三方通知渠道id';
COMMENT ON COLUMN third_notice.params IS '通知参数';
COMMENT ON COLUMN third_notice.status IS '1:启用 2:禁用';
COMMENT ON COLUMN third_notice.created_at IS '创建时间';
COMMENT ON COLUMN third_notice.updated_at IS '更新时间';
COMMENT ON COLUMN third_notice.deleted_at IS '删除时间';

DROP TABLE IF EXISTS third_notice_channel;

CREATE TABLE third_notice_channel (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(100) NOT NULL DEFAULT '',
                                      type SMALLINT NOT NULL DEFAULT 0,
                                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      deleted_at TIMESTAMP DEFAULT NULL
);

COMMENT ON TABLE third_notice_channel IS '三方通知渠道';

COMMENT ON COLUMN third_notice_channel.id IS '主键id';
COMMENT ON COLUMN third_notice_channel.name IS '名称';
COMMENT ON COLUMN third_notice_channel.type IS '类型 1:飞书  2:企业微信  3:邮箱  4:钉钉';
COMMENT ON COLUMN third_notice_channel.created_at IS '创建时间';
COMMENT ON COLUMN third_notice_channel.updated_at IS '更新时间';
COMMENT ON COLUMN third_notice_channel.deleted_at IS '删除时间';

